version: '3'

services:
  histogram-sv:
    build:
      context: ./histogram
      dockerfile: Dockerfile
    ports:
      - 5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0
  histogram-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:80