flask:
    APP_DIR: "."
    PROJECT_ROOT: "."
    env: 'development'
    debug: True
    host: '0.0.0.0'
db: 
    host: '127.0.0.1'
    port: 27017
    database: 'histogram'
source_provider:
    browser: /usr/bin/chromedriver